# Generated by Django 3.2.2 on 2021-05-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valsamis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='companyname',
            new_name='name',
        ),
    ]
