# Generated by Django 4.0.4 on 2023-01-13 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valsamis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='user',
        ),
    ]
