# Generated by Django 4.0.4 on 2023-01-13 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('valsamis', '0003_ship_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ship',
            old_name='user',
            new_name='created_user',
        ),
        migrations.AddField(
            model_name='ship',
            name='edited_user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ship',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ship',
            name='typeship',
            field=models.CharField(blank=True, choices=[('c', 'Cruise ship'), ('t', 'Tanker'), ('p', 'Passenger Ship'), ('o', 'Other')], default='c', max_length=1),
        ),
    ]
