# Generated by Django 3.2.2 on 2021-05-10 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valsamis', '0003_auto_20210510_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branches',
            old_name='branchtype',
            new_name='title',
        ),
    ]
