# Generated by Django 4.0.4 on 2023-01-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valsamis', '0004_rename_user_ship_created_user_ship_edited_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='typeship',
            field=models.CharField(blank=True, choices=[('Cruise ship', 'cruise ship'), ('Tanker', 'tanker'), ('Passenger Ship', 'passenger Ship'), ('Other', 'other')], default='Cruise ship', max_length=100),
        ),
    ]
