# Generated by Django 3.2.2 on 2021-05-13 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valsamis', '0004_rename_branchtype_branches_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the project name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the ship name', max_length=200)),
                ('shiptype', models.TextField(help_text='Enter the type of ship', max_length=1000)),
                ('status', models.CharField(blank=True, choices=[('c', 'Cruise ship'), ('t', 'Tanker'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='What type of ship is it', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='companyinstance',
            name='branches',
        ),
        migrations.RemoveField(
            model_name='companyinstance',
            name='company',
        ),
        migrations.RemoveField(
            model_name='company',
            name='branches',
        ),
        migrations.DeleteModel(
            name='Branches',
        ),
        migrations.DeleteModel(
            name='CompanyInstance',
        ),
        migrations.AddField(
            model_name='ship',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='valsamis.company'),
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='valsamis.company'),
        ),
        migrations.AddField(
            model_name='project',
            name='ship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='valsamis.ship'),
        ),
    ]
