# Generated by Django 4.0.4 on 2023-01-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valsamis', '0005_alter_ship_typeship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
