# Generated by Django 4.0.4 on 2023-08-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valsamis', '0006_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalitem',
            name='category',
            field=models.CharField(default='testing', help_text='Enter the category', max_length=200),
        ),
        migrations.AddField(
            model_name='generalitem',
            name='group',
            field=models.CharField(default='testing', help_text='Enter the group', max_length=200),
        ),
        migrations.AddField(
            model_name='generalitem',
            name='subgroup',
            field=models.CharField(default='testing', help_text='Enter the subgroup', max_length=200),
        ),
        migrations.AlterField(
            model_name='materialitemregister',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='pochoices',
            field=models.CharField(blank=True, choices=[('M', 'Material'), ('L', 'Logistics'), ('T', 'Travel'), ('O', 'Other')], default='M', max_length=1),
        ),
    ]
