# Generated by Django 3.2.2 on 2022-01-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valsamis', '0007_auto_20210513_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, help_text='any notes for the project', max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='subproject',
        ),
    ]
