# Generated by Django 3.2.2 on 2022-01-21 16:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('valsamis', '0008_auto_20220121_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='POmaterialDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('itemdescription', models.TextField(blank=True, help_text='Enter the description of the item', max_length=1000)),
                ('unit', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('currency', models.CharField(choices=[('U', 'US Dollars'), ('E', 'Euros'), ('P', 'Pesos')], default='U', max_length=1)),
                ('suppliercode', models.CharField(blank=True, help_text='Enter Supplier Code if you can', max_length=40)),
                ('notes', models.TextField(help_text='Enter any notes for this item', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('typePO', models.CharField(choices=[('M', 'Material'), ('L', 'Logistics'), ('T', 'Travel'), ('O', 'Other')], default='m', max_length=1)),
                ('notes', models.TextField(blank=True, help_text='any notes for PO?', max_length=1000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='valsamis.project')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='valsamis.supplier')),
            ],
        ),
    ]
