# Generated by Django 3.2.2 on 2022-01-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valsamis', '0009_po_pomaterialdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pomaterialdetail',
            old_name='itemdescription',
            new_name='item_description',
        ),
        migrations.RenameField(
            model_name='pomaterialdetail',
            old_name='suppliercode',
            new_name='supplier_code',
        ),
        migrations.AlterField(
            model_name='pomaterialdetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
