# Generated by Django 4.0.4 on 2023-08-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valsamis', '0009_alter_ship_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_info',
            field=models.CharField(default='testing', help_text='Enter the location (optional)', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(default='testing', help_text='Enter the type of company (ship, ...)', max_length=200),
        ),
    ]
