# Generated by Django 4.0.4 on 2023-08-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valsamis', '0010_company_contact_info_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='PObox',
            field=models.CharField(default='testing', help_text='Enter the customer PO box', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='address1',
            field=models.CharField(default='testing', help_text='Enter the customer address', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='testing', help_text='Enter the customer country', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='testing', help_text='Enter the customer email', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.CharField(default='testing', help_text='Enter any notes about this customer', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='testing', help_text='Enter the customer phone number', max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='PObox',
            field=models.CharField(default='testing', help_text='Enter the supplier PO box', max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address1',
            field=models.CharField(default='testing', help_text='Enter the supplier address', max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(default='testing', help_text='Enter the supplier country', max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.CharField(default='testing', help_text='Enter the supplier email', max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='notes',
            field=models.CharField(default='testing', help_text='Enter any notes about this supplier', max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(default='testing', help_text='Enter the supplier phone number', max_length=200),
        ),
    ]
