# Generated by Django 3.2.2 on 2022-01-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valsamis', '0011_rename_po_purchaseorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='POmaterialDetail',
            new_name='ItemRegister',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
