# Generated by Django 4.0.4 on 2023-08-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valsamis', '0012_project_disembarkation_project_embarkation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.TextField(default='testing', help_text='Enter the project manager', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='typeship',
            field=models.CharField(blank=True, choices=[('Inspection', 'Inspection'), ('Dry Dock', 'Dry Dock'), ('Shop', 'Shop'), ('Fabrication', 'Fabrication')], default='Inspection', max_length=100),
        ),
    ]
