# Generated by Django 4.0.4 on 2023-08-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valsamis', '0013_project_manager_project_typeship'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location_info',
            field=models.CharField(default='testing', help_text='Enter the location (optional)', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_info',
            field=models.CharField(default='testing', help_text='Enter the contact info (optional)', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='materialitemregister',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
