# Generated by Django 3.2.2 on 2022-01-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valsamis', '0014_alter_purchaseorder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemregister',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemregister',
            name='item_description',
            field=models.TextField(help_text='Enter the description of the item', max_length=1000, null=True),
        ),
    ]
