# Generated by Django 3.2.2 on 2022-01-21 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valsamis', '0015_auto_20220121_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemregister',
            name='PurchaseOrder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='valsamis.purchaseorder'),
        ),
    ]
