# Generated by Django 4.0.4 on 2023-08-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valsamis', '0015_alter_generalitem_category_alter_generalitem_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialitemregister',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
