# Generated by Django 3.2.6 on 2022-01-22 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valsamis', '0017_auto_20220121_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='generalitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the general item name', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='materialitemregister',
            name='generalitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='valsamis.generalitem'),
        ),
    ]
