# Generated by Django 3.2.6 on 2022-02-01 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valsamis', '0019_alter_purchaseorder_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='typePO',
            new_name='POtype',
        ),
    ]
