# Generated by Django 3.2.6 on 2022-02-01 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valsamis', '0020_rename_typepo_purchaseorder_potype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='POtype',
        ),
    ]
