# Generated by Django 3.2.6 on 2022-02-08 01:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('valsamis', '0021_remove_purchaseorder_potype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialitemregister',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for purchase', primary_key=True, serialize=False),
        ),
    ]
