# Generated by Django 3.2.6 on 2022-02-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valsamis', '0022_alter_materialitemregister_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialitemregister',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
